#!/bin/bash

if [ "$EUID" -eq 0 ]
  then xhost + || true
  exit
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'

if ! [[ $(which npm) = *"8.11.2"* ]]; then
        nvm install v8.11.2
        nvm alias default v8.11.2
fi

unalias grv 2>/dev/null

export PATH=$PATH:~/.local/bin

alias grep_js='grep -ir --exclude-dir=node_modules  --include=*.js --exclude-dir=dist '
alias grep_ts='grep -ir --exclude-dir=node_modules  --include=*.ts --exclude-dir=dist '
alias grep_html='grep -ir --exclude-dir=node_modules  --include=*.html --exclude-dir=dist '
alias grep_css='grep -ir --exclude-dir=node_modules  --include=*.css --include=*.scss --exclude-dir=dist '
alias grep_package_json='grep -ir --exclude-dir=000.INFRA --exclude-dir=node_modules  --include=package.json '

alias move_gitea='git remote remove origin; git remote add origin http://gitea:3000/gbencke/$(basename $(pwd)).git ; git push origin --all'

cd

