#To be added after the Oh-My-Zsh zshrc script

if [ "$EUID" -eq 0 ]
  then xhost + || true
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'

if ! [[ $(which npm) = *"18.17.1"* ]]; then
        nvm install v18.17.1
        nvm alias default v18.17.1
fi

unalias grv 2>/dev/null

export DEFAULT_AVD=Teste
export ANDROID_HOME=~/Android/Sdk
export QT_QPA_PLATFORMTHEME='qt5ct'

export PATH=$PATH:~/.local/bin:/usr/local/lib/libreoffice/program:/home/gbencke/Android/Sdk/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/emulator

ZSH_THEME="clean"

alias grep_js='grep -ir --exclude-dir=node_modules  --include \*.js --include \*.jsx --exclude-dir=dist '
alias grep_jsx='grep -ir --exclude-dir=node_modules  --include \*.js --include \*.jsx --exclude-dir=dist '
alias grep_ts='grep -ir --exclude-dir=node_modules  --include \*.ts --exclude-dir=dist '
alias grep_html='grep -ir --exclude-dir=node_modules  --include \*.html --exclude-dir=dist '
alias grep_css='grep -ir --exclude-dir=node_modules  --include \*.css --include \*.scss --exclude-dir=dist '
alias grep_package_json='grep -ir --exclude-dir=000.INFRA --exclude-dir=node_modules  --include=package.json '

alias homebrew='HOMEBREW_NO_AUTO_UPDATE=1 brew install '
alias move_gitea='git remote remove origin; git remote add origin http://gitea:3000/gbencke/$(basename $(pwd)).git ; git push origin --all'
alias node_modules_jest='tsc; node --inspect-brk node_modules/jest/bin/jest.js'

alias jt=/opt/jetbrains-toolbox/jetbrains-toolbox
alias vim=nvim 
alias gvim=nvim 

switch_bencke_func(){
    cp ~/.aws/config.bencke ~/.aws/config;
    cp ~/.aws/credentials.bencke ~/.aws/credentials;
    unset AWS_PROFILE;
}

switch_serviceai_func(){
    cp ~/.aws/config.serviceai ~/.aws/config; 
    cp ~/.aws/credentials.serviceai ~/.aws/credentials;
    export AWS_PROFILE=serviceai-prod;
}

remove_husky(){
    sed -i -e 's/hooksPath = .husky//g' .git/config
}

remove_cdkout(){
    find . -type d -name cdk.out -exec rm -rf {} \;  
}

remove_node_modules(){
    find . -type d -name node_modules -exec rm -rf {} \;  
}

alias switch_bencke=switch_bencke_func
alias switch_serviceai=switch_serviceai_func
alias removeHusky=remove_husky
alias removeCdkout=remove_cdkout


export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

cd

