# To be added after the Oh-My-Zsh zshrc script

export CHROME_BIN=$(which chromium)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'

if ! [[ $(which npm) = *"8.11.2"* ]]; then
        nvm install v8.11.2
        nvm alias default v8.11.2
fi

unalias grv 2>/dev/null

export PATH=$PATH:~/.local/bin

ZSH_THEME="clean"

cd

